#define DO                  "AT"
#define NOW                 "\r"
#define REDO                "A/"

#define DATA_TO_COMMAND     "+++"
#define COMMAND_TO_DATA     "ATO"

#define ANSWER              "ATA"
#define CALL                "ATD"
#define RECALL              "ATDL"
#define DISCONNECT          "ATH"

#define ECHO                "ATE"
#define IDENTIFY            "ATI"
#define SPEAKER_LOUDNESS    "ATL"
#define SPEAKER_MODE        "ATM"
#define PULSE               "ATP"
#define NORESULT            "ATQ"
#define NUMBER_RINGS        "ATS0"
#define LINE_TERMIN_CHAR    "ATS3"
#define RESP_FORMAT_CHAR    "ATS4"
#define LINE_EDIT_CHAR      "ATS5"
#define PAUSE_BEFORE_BLIND_DIALING  "ATS6"
#define SEC_WAIT_CONN_COMPLETE      "ATS7"
#define SEC_WAIT_COMMA              "ATS8"
#define DISCONN_DELAY_ABS_DATA_CARRIER  "ATS10"
#define SELECT_TONE_DIALING             "ATT"
#define TA_RESP_FORMAT                  "ATV"
#define CONN_RESULT_CODE_AND_MONITOR_CALL "ATX"
#define RESET_DEFAULT_CONFIG              "ATZ"
#define DCD_FUNC_MODE                     "AT&C"
#define DTR_FUNC_MODE                     "AT&D"
#define FACTORY_DEF_CONFIG                "AT&F"
#define DISP_CURR_CONFIG                  "AT&V"
#define STORE_